blog/urls.py
from django.conf.urls import url
from . import views


app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^category/(?P<category>\w+)/$', views.get_filter_category, name='category_filter'),
    url(r'^category/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<tag>\w+)/$', views.get_filter_tags, name='tags'),
]

secondblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
import markdown
from django.utils.html import strip_tags


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=70)

    body = models.TextField()

    created_time = models.DateField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)

    excerpt = models.CharField(max_length=200, blank=True)

    category = models.ForeignKey(Category)
    tags = models.ManyToManyField(Tag, blank=True)

    author = models.ForeignKey(User)
    # 文章访问量
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        # 如果没有填写摘要
        if not self.excerpt:
            # 首先实例化一个 Markdown 类，用于渲染 body 的文本
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            # 先将 Markdown 文本渲染成 HTML 文本
            # strip_tags 去掉 HTML 文本的全部 HTML 标签
            # 从文本摘取前 54 个字符赋给 excerpt
            self.excerpt = strip_tags(md.convert(self.body))[:54]

        # 调用父类的 save 方法将数据保存到数据库中
        super(Post, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-created_time']  # 日期只精确到天的话,同一天发布多篇文章,文章顺序有问题

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Tag, Category
from django.views.generic import ListView, DetailView
from markdown.extensions.toc import TocExtension
from django.utils.text import slugify
import markdown


class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        """
        在视图函数中将模板变量传递给模板是通过给 render 函数的 context 参数传递一个字典实现的，
        例如 render(request, 'blog/index.html', context={'post_list': post_list})，
        这里传递了一个 {'post_list': post_list} 字典给模板。
        在类视图中，这个需要传递的模板变量字典是通过 get_context_data 获得的，
        所以我们复写该方法，以便我们能够自己再插入一些我们自定义的模板变量进去。
        """

        # 首先获得父类生成的传递给模板的字典。
        context = super().get_context_data(**kwargs)

        # 父类生成的字典中已有 paginator、page_obj、is_paginated 这三个模板变量，
        # paginator 是 Paginator 的一个实例，
        # page_obj 是 Page 的一个实例，
        # is_paginated 是一个布尔变量，用于指示是否已分页。
        # 例如如果规定每页 10 个数据，而本身只有 5 个数据，其实就用不着分页，此时 is_paginated=False。
        # 关于什么是 Paginator，Page 类在 Django Pagination 简单分页：http://zmrenwu.com/post/34/ 中已有详细说明。
        # 由于 context 是一个字典，所以调用 get 方法从中取出某个键对应的值。
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')

        # 调用自己写的 pagination_data 方法获得显示分页导航条需要的数据，见下方。
        pagination_data = self.pagination_data(paginator, page, is_paginated)

        # 将分页导航条的模板变量更新到 context 中，注意 pagination_data 方法返回的也是一个字典。
        context.update(pagination_data)

        # 将更新后的 context 返回，以便 ListView 使用这个字典中的模板变量去渲染模板。
        # 注意此时 context 字典中已有了显示分页导航条所需的数据。
        return context

    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            # 如果没有分页，则无需显示分页导航条，不用任何分页导航条的数据，因此返回一个空的字典
            return {}

        # 当前页左边连续的页码号，初始值为空
        left = []

        # 当前页右边连续的页码号，初始值为空
        right = []

        # 标示第 1 页页码后是否需要显示省略号
        left_has_more = False

        # 标示最后一页页码前是否需要显示省略号
        right_has_more = False

        # 标示是否需要显示第 1 页的页码号。
        # 因为如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
        # 其它情况下第一页的页码是始终需要显示的。
        # 初始值为 False
        first = False

        # 标示是否需要显示最后一页的页码号。
        # 需要此指示变量的理由和上面相同。
        last = False

        # 获得用户当前请求的页码号
        page_number = page.number

        # 获得分页后的总页数
        total_pages = paginator.num_pages

        # 获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
        page_range = paginator.page_range

        if page_number == 1:
            # 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
            # 此时只要获取当前页右边的连续页码号，
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
            # 注意这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            right = page_range[page_number:page_number + 2]

            # 如果最右边的页码号比最后一页的页码号减去 1 还要小，
            # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
            if right[-1] < total_pages - 1:
                right_has_more = True

            # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
            # 所以需要显示最后一页的页码号，通过 last 来指示
            if right[-1] < total_pages:
                last = True

        elif page_number == total_pages:
            # 如果用户请求的是最后一页的数据，那么当前页右边就不需要数据，因此 right=[]（已默认为空），
            # 此时只要获取当前页左边的连续页码号。
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
            # 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]

            # 如果最左边的页码号比第 2 页页码号还大，
            # 说明最左边的页码号和第 1 页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示。
            if left[0] > 2:
                left_has_more = True

            # 如果最左边的页码号比第 1 页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码，
            # 所以需要显示第一页的页码号，通过 first 来指示
            if left[0] > 1:
                first = True
        else:
            # 用户请求的既不是最后一页，也不是第 1 页，则需要获取当前页左右两边的连续页码号，
            # 这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]

            # 是否需要显示最后一页和最后一页前的省略号
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True

            # 是否需要显示第 1 页和第 1 页后的省略号
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }

        return data

class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get_object(self, queryset=None):
        post = super(PostDetailView, self).get_object(queryset=None)
        # 覆写 get_object 方法的目的是因为需要对 post 的 body 值进行渲染
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            TocExtension(slugify=slugify),
        ])
        post.body = md.convert(post.body)
        post.toc = md.toc
        return post

class CategoryView(ListView):
    model = Post
    template_name = 'blog/category.html'
    context_object_name = 'post_list'
    """
    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)
    """


def get_filter_category(request, category):
    post_list = Post.objects.filter(category__name=category)
    return render(request, 'blog/category.html', context={'post_list': post_list})



def get_filter_tags(request, tag):
    post_list = Post.objects.filter(tags__name=tag)
    return render(request, 'blog/index.html', context={'post_list': post_list})

blog/templates/base.html
{% load static %}
{% load blog_tags %}

<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>Xiaoyaook's Blog</title>
    <link rel="stylesheet" href="{% static 'blog/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/nav.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/xiaoyaook.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'blog/img/favicon.ico' %}">
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">
    <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
</head>
<body>
    <header>
        <nav id='cssmenu'>
            <ul>
               <li class='active'><a href="{% url 'blog:index' %}">Home</a></li>
               <li><a href="{% url 'blog:category' %}">Category</a></li>
               <li><a href="#">Contact</a></li>
            </ul>
        </nav>
    </header>
    {% block upside %}
    {% endblock %}
    <div class="container-fluid">
        <div class="row">
            <main class="col-md-8 col-md-offset-2">
                {% block main %}
                {% endblock %}
            </main>
        </div>
    </div>
    <footer><p class="text-center">Write by xiaoyaook</p></footer>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    <script src="{% static 'blog/js/script.js' %}"></script>
</body>
</html>

blog/templates/blog/category.html
{% extends 'blog/index.html' %}
{% load blog_tags %}

{% block upside %}
    <div class="up-aside">
        <div class="container">
            <h1 id="category-title">Category</h1>
            <nav class="category-nav">
                {% get_categories as category_list %}
                <ul class="category-list">
                        <li class="category-list-item">
                            <a href="{% url 'blog:category' %}">All</a>
                        </li>
                        {% for category in category_list %}
                        <li class="category-list-item">
                            <a href="{% url 'blog:category_filter' category.name %}">{{ category.name }}</a>
                        </li>
                        {% endfor %}
                    </ul>
            </nav>
        </div>

    </div>
{% endblock %}

blog/templates/blog/detail.html
{% extends 'base.html' %}

{% block main %}
    <article class="post-article">
        <div class="post-card">
            <h1 class="post-card-title">{{ post.title }}</h1>
            <div class="post-meta">{{ post.created_time }}</div>
            <div class="post-content">{{ post.body|safe }}</div>
        </div>
    </article>
{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}

{% block upside %}
    <div class="up-aside">
        <p class="logo focus-in-expand text-center">Xiaoyaook</p>
    </div>
{% endblock %}

{% block main %}
    <div class="main-contained">
        <ul class="post-list">
            {% for post in post_list %}
                <li class="post-list-item">
                    <article class="article-card">
                        <h3 class="post-title"><a class="post-title-link" href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                        <div class="post-meta">{{ post.created_time}}</div>
                        <div class="post-description">
                            <!-- 从正文截取部分文字作为描述 -->
                            <p>{{ post.excerpt }}...
                                <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                            </p>
                        </div>
                        {% if post.tags %}
                            <div class="post-footer">
                                <ul class="tag-list">
                                    {% for tag in post.tags.all %}
                                        <li class="tag-list-item"><a class="tag-list-item-link" href="{% url 'blog:tags' tag %}">{{ tag }}</a></li>
                                    {% endfor %}
                                </ul>
                            </div>
                        {% endif %}
                    </article>
                </li>
            {% empty %}
                <div class="no-post">暂时没有发布的文章</div>
            {% endfor %}
        </ul>

        {% if is_paginated %}
        <nav class="text-center" aria-label="Page navigation">
            <ul class="pagination">
                <li>
                    <a href="#" aria-label="Previous">
                      <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% if first %}
                <li><a href="#">1</a></li>
                {% endif %}

                {% if left %}
                    {% if left_has_more %}
                    <span>...</span>
                    {% endif %}
                {% for i in left %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
                {% endfor %}
                {% endif %}

                <li><a href="?page={{ page_obj.number }}" style="color: red">{{ page_obj.number }}</a></li>

                {% if right %}
                {% for i in right %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
                {% endfor %}
                    {% if right_has_more %}
                    <span>...</span>
                    {% endif %}
                {% endif %}

                {% if last %}
                <li><a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
                {% endif %}
                <li>
                  <a href="#" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                  </a>
                </li>
            </ul>
        </nav>
        {% endif %}
    </div>
{% endblock %}